Use registro;

DELIMITER \\

CREATE TRIGGER actualizar_empleado AFTER UPDATE ON empleado
	FOR EACH ROW
BEGIN
	INSERT INTO bitacora_empleado(CODEMPLEADO, NOMBRE_EMPLEADO, APELLIDO_EMPLEADO, DIRECCION_EMPLEADO, 
    TELEFONO_EMPLEADO, SEXO_EMPLEADO, SALARIO_EMPLEADO, CI_EMPLEADO, EDAD, EMPLEADO, Movimiento)
    VALUES (null, new.NOMBRE_EMPLEADO, new.APELLIDO_EMPLEADO, new.DIRECCION_EMPLEADO, new.TELEFONO_EMPLEADO, 
    new.SEXO_EMPLEADO, new.SALARIO_EMPLEADO, new.CI_EMPLEADO, new.EDAD, new.EDAD, new.EMPLEADO, 'UPDATE');
END \\