Use registro;

DELIMITER \\

CREATE TRIGGER borrar_cliente AFTER DELETE ON cliente
	FOR EACH ROW
BEGIN
	INSERT INTO bitacora_cliente(SEXO_CLIENTE, Codbit, NOMBRE_CLIENTE, APELLIDO_CLIENTE, DIRECCION_CLIENTE, TELEFONO_CLIENTE, Movimiento)
    VALUES (old.SEXO_CLIENTE, null, old.NOMBRE_CLIENTE, old.APELLIDO_CLIENTE, old.DIRECCION_CLIENTE,
    old.TELEFONO_CLIENTE, 'DELETE');
END \\